# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/12_Zynq_mini/12_UART_IP_TEST/12_UART_IP_TEST/12_UART_IP_TEST.srcs/sources_1/bd/system/ip/system_UART_IP_NCY_0_0/system_UART_IP_NCY_0_0.xci
# IP: The module: 'system_UART_IP_NCY_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/12_Zynq_mini/12_UART_IP_TEST/12_UART_IP_TEST/12_UART_IP_TEST.gen/sources_1/bd/system/ip/system_UART_IP_NCY_0_0/src/zynq_mini.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_UART_IP_NCY_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: E:/12_Zynq_mini/12_UART_IP_TEST/12_UART_IP_TEST/12_UART_IP_TEST.srcs/sources_1/bd/system/ip/system_UART_IP_NCY_0_0/system_UART_IP_NCY_0_0.xci
# IP: The module: 'system_UART_IP_NCY_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/12_Zynq_mini/12_UART_IP_TEST/12_UART_IP_TEST/12_UART_IP_TEST.gen/sources_1/bd/system/ip/system_UART_IP_NCY_0_0/src/zynq_mini.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_UART_IP_NCY_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
