set_property SRC_FILE_INFO {cfile:E:/12_Zynq_mini/12_UART_IP_TEST/12_UART_IP_TEST/12_UART_IP_TEST.srcs/constrs_1/imports/12_Zynq_mini/zynq_mini.xdc rfile:../../../12_UART_IP_TEST.srcs/constrs_1/imports/12_Zynq_mini/zynq_mini.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U15 IOSTANDARD LVCMOS33} [get_ports tx]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN P15 IOSTANDARD LVCMOS33} [get_ports rx]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/reg2_reg_n_0_[1]}]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/reg2_reg_n_0_[6]}]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/reg2_reg_n_0_[11]}]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/reg2_reg_n_0_[13]}]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/reg2_reg_n_0_[18]}]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/reg2_reg_n_0_[20]}]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/reg2_reg_n_0_[24]}]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/reg2_reg_n_0_[31]}]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/reg2_reg_n_0_[5]}]
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/reg2_reg_n_0_[17]}]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/reg2_reg_n_0_[19]}]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/reg2_reg_n_0_[22]}]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/reg2_reg_n_0_[23]}]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/reg2_reg_n_0_[25]}]
set_property src_info {type:XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/reg2_reg_n_0_[30]}]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/reg2_reg_n_0_[2]}]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/reg2_reg_n_0_[8]}]
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/reg2_reg_n_0_[10]}]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/reg2_reg_n_0_[14]}]
set_property src_info {type:XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/reg2_reg_n_0_[28]}]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/reg2_reg_n_0_[29]}]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/reg2_reg_n_0_[15]}]
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/reg2_reg_n_0_[4]}]
set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/reg2_reg_n_0_[0]}]
set_property src_info {type:XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/reg2_reg_n_0_[3]}]
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/reg2_reg_n_0_[7]}]
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/reg2_reg_n_0_[9]}]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/reg2_reg_n_0_[12]}]
set_property src_info {type:XDC file:1 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/reg2_reg_n_0_[26]}]
set_property src_info {type:XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/reg2_reg_n_0_[27]}]
set_property src_info {type:XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/reg2_reg_n_0_[16]}]
set_property src_info {type:XDC file:1 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/reg2_reg_n_0_[21]}]
set_property src_info {type:XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/rx_data[0]}]
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/rx_data[1]}]
set_property src_info {type:XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/rx_data[2]}]
set_property src_info {type:XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/rx_data[3]}]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/rx_data[4]}]
set_property src_info {type:XDC file:1 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/rx_data[5]}]
set_property src_info {type:XDC file:1 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/rx_data[6]}]
set_property src_info {type:XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/rx_data[7]}]
set_property src_info {type:XDC file:1 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/RX_current_state[0]}]
set_property src_info {type:XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/RX_current_state[1]}]
set_property src_info {type:XDC file:1 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/RX_current_state[2]}]
set_property src_info {type:XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/RX_current_state[3]}]
set_property src_info {type:XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:1 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 8192 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:1 line:67 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list system_i/processing_system7_0/inst/FCLK_CLK0]]
set_property src_info {type:XDC file:1 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:70 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {system_i/UART_IP_NCY_0/inst/U0_UART/rx_data[0]} {system_i/UART_IP_NCY_0/inst/U0_UART/rx_data[1]} {system_i/UART_IP_NCY_0/inst/U0_UART/rx_data[2]} {system_i/UART_IP_NCY_0/inst/U0_UART/rx_data[3]} {system_i/UART_IP_NCY_0/inst/U0_UART/rx_data[4]} {system_i/UART_IP_NCY_0/inst/U0_UART/rx_data[5]} {system_i/UART_IP_NCY_0/inst/U0_UART/rx_data[6]} {system_i/UART_IP_NCY_0/inst/U0_UART/rx_data[7]}]]
set_property src_info {type:XDC file:1 line:71 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 4 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:74 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {system_i/UART_IP_NCY_0/inst/U0_UART/RX_current_state[0]} {system_i/UART_IP_NCY_0/inst/U0_UART/RX_current_state[1]} {system_i/UART_IP_NCY_0/inst/U0_UART/RX_current_state[2]} {system_i/UART_IP_NCY_0/inst/U0_UART/RX_current_state[3]}]]
set_property src_info {type:XDC file:1 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:78 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets clk]
