#set_property -dict { PACKAGE_PIN K17 IOSTANDARD LVCMOS33} [get_ports {clk}]
#set_property -dict { PACKAGE_PIN M19 IOSTANDARD LVCMOS33} [get_ports {reset}]
set_property -dict {PACKAGE_PIN U15 IOSTANDARD LVCMOS33} [get_ports tx]
set_property -dict {PACKAGE_PIN P15 IOSTANDARD LVCMOS33} [get_ports rx]

#set_property -dict { PACKAGE_PIN T12 IOSTANDARD LVCMOS33} [get_ports {LED[0]}]
#set_property -dict { PACKAGE_PIN U12 IOSTANDARD LVCMOS33} [get_ports {LED[1]}]
#set_property -dict { PACKAGE_PIN V12 IOSTANDARD LVCMOS33} [get_ports {LED[2]}]
#set_property -dict { PACKAGE_PIN W13 IOSTANDARD LVCMOS33} [get_ports {LED[3]}]

set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/reg2_reg_n_0_[1]}]
set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/reg2_reg_n_0_[6]}]
set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/reg2_reg_n_0_[11]}]
set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/reg2_reg_n_0_[13]}]
set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/reg2_reg_n_0_[18]}]
set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/reg2_reg_n_0_[20]}]
set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/reg2_reg_n_0_[24]}]
set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/reg2_reg_n_0_[31]}]
set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/reg2_reg_n_0_[5]}]
set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/reg2_reg_n_0_[17]}]
set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/reg2_reg_n_0_[19]}]
set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/reg2_reg_n_0_[22]}]
set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/reg2_reg_n_0_[23]}]
set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/reg2_reg_n_0_[25]}]
set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/reg2_reg_n_0_[30]}]
set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/reg2_reg_n_0_[2]}]
set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/reg2_reg_n_0_[8]}]
set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/reg2_reg_n_0_[10]}]
set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/reg2_reg_n_0_[14]}]
set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/reg2_reg_n_0_[28]}]
set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/reg2_reg_n_0_[29]}]
set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/reg2_reg_n_0_[15]}]
set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/reg2_reg_n_0_[4]}]
set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/reg2_reg_n_0_[0]}]
set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/reg2_reg_n_0_[3]}]
set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/reg2_reg_n_0_[7]}]
set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/reg2_reg_n_0_[9]}]
set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/reg2_reg_n_0_[12]}]
set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/reg2_reg_n_0_[26]}]
set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/reg2_reg_n_0_[27]}]
set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/reg2_reg_n_0_[16]}]
set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/reg2_reg_n_0_[21]}]
set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/rx_data[0]}]
set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/rx_data[1]}]
set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/rx_data[2]}]
set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/rx_data[3]}]
set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/rx_data[4]}]
set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/rx_data[5]}]
set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/rx_data[6]}]
set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/rx_data[7]}]
set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/RX_current_state[0]}]
set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/RX_current_state[1]}]
set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/RX_current_state[2]}]
set_property MARK_DEBUG true [get_nets {system_i/UART_IP_NCY_0/inst/U0_UART/RX_current_state[3]}]


create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 8192 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list system_i/processing_system7_0/inst/FCLK_CLK0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 8 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {system_i/UART_IP_NCY_0/inst/U0_UART/rx_data[0]} {system_i/UART_IP_NCY_0/inst/U0_UART/rx_data[1]} {system_i/UART_IP_NCY_0/inst/U0_UART/rx_data[2]} {system_i/UART_IP_NCY_0/inst/U0_UART/rx_data[3]} {system_i/UART_IP_NCY_0/inst/U0_UART/rx_data[4]} {system_i/UART_IP_NCY_0/inst/U0_UART/rx_data[5]} {system_i/UART_IP_NCY_0/inst/U0_UART/rx_data[6]} {system_i/UART_IP_NCY_0/inst/U0_UART/rx_data[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 4 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {system_i/UART_IP_NCY_0/inst/U0_UART/RX_current_state[0]} {system_i/UART_IP_NCY_0/inst/U0_UART/RX_current_state[1]} {system_i/UART_IP_NCY_0/inst/U0_UART/RX_current_state[2]} {system_i/UART_IP_NCY_0/inst/U0_UART/RX_current_state[3]}]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk]
