# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/12_Zynq_mini/zynq_mini.xdc

# Block Designs: bd/system/system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_ps7_0_axi_periph_0/system_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_ps7_0_axi_periph_0 || ORIG_REF_NAME==system_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/system/ip/system_rst_ps7_0_50M_0/system_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rst_ps7_0_50M_0 || ORIG_REF_NAME==system_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/system/ip/system_processing_system7_0_1/system_processing_system7_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_processing_system7_0_1 || ORIG_REF_NAME==system_processing_system7_0_1} -quiet] -quiet

# IP: bd/system/ip/system_system_ila_0_1/system_system_ila_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_system_ila_0_1 || ORIG_REF_NAME==system_system_ila_0_1} -quiet] -quiet

# IP: bd/system/ip/system_UART_IP_NCY_0_0/system_UART_IP_NCY_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_UART_IP_NCY_0_0 || ORIG_REF_NAME==system_UART_IP_NCY_0_0} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_0/system_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_auto_pc_0 || ORIG_REF_NAME==system_auto_pc_0} -quiet] -quiet

# XDC: e:/12_Zynq_mini/12_UART_IP_TEST/12_UART_IP_TEST/12_UART_IP_TEST.gen/sources_1/bd/system/system_ooc.xdc
